tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Build tooling for Clojure
brew "boot-clj"
# Library for command-line editing
brew "readline"
# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"
# The Clojure Programming Language
brew "clojure"
# Cross-platform make
brew "cmake"
# Tool for browsing source code
brew "cscope"
# USB programmer
brew "dfu-util"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# H.264/AVC encoder
brew "x264"
# High-performance, high-quality MPEG-4 video library
brew "xvid"
# General-purpose data compression with high compression ratio
brew "xz"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Library for manipulating PNG images
brew "libpng"
# Software library to render fonts
brew "freetype"
# Image manipulation library
brew "jpeg"
# TIFF library and utilities
brew "libtiff"
# GNU database manager
brew "gdbm"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# GIF image/animation creator/editor
brew "gifsicle"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Add GitHub support to git on the command-line
brew "hub"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# malloc implementation emphasizing fragmentation avoidance
brew "jemalloc"
# Build tool for Clojure
brew "leiningen"
# SSL/TLS cryptography library
brew "openssl"
# Asynchronous event library
brew "libevent"
# C string library for manipulating Unicode strings
brew "libunistring"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Library for processing keyboard entry from the terminal
brew "libtermkey"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# C99 library which implements a VT220 or xterm terminal emulator
brew "libvterm"
# YAML Parser
brew "libyaml"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Powerful, lightweight programming language
brew "lua"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Creates dependencies in makefiles
brew "makedepend"
# Library for a binary-based efficient data interchange format
brew "msgpack"
# NCurses Disk Usage
brew "ncdu"
# Very basic terminfo library
brew "unibilium"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Perl compatible regular expressions library
brew "pcre"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Highly capable, feature-rich programming language
brew "perl"
# Manage compile and link flags for libraries
brew "pkg-config"
# Stand-alone ClojureScript REPL
brew "planck"
# Optimizer for PNG files
brew "pngcrush"
# Monitor data's progress through a pipe
brew "pv"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Interpreted, interactive, object-oriented programming language
brew "python@2"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby", link: true
# Programatically correct mistyped console commands
brew "thefuck"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
cask "hammerspoon"
cask "hyper"
