source ~/.vim/plugins.vim
" "Plugin Configurations
source ~/.vim/plugin-config.vim

" Mappings
source ~/.vim/mappings.vim

" Configuration options
source ~/.vim/config.vim

if has('nvim')
    tnoremap <Esc> <C-\><C-n>
    set inccommand=nosplit " Preview changes live when using :s/ or :%s/
endif

" colorscheme vimspectr60-light
colorscheme seoul256


let g:python3_host_prog = expand('~/.config/nvim/py_env/bin/python')
